Chill\CustomFieldsBundle\Entity\CustomField:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: json_array
        slug:
            type: string
            length: 255
        type:
            type: string
            length: 255
        active:
            type: boolean
        ordering:
            type: float
        options:
            type: json_array
        required:
            type: boolean
    lifecycleCallbacks: {  }
    manyToOne:
        customFieldGroup:
            targetEntity: Chill\CustomFieldsBundle\Entity\CustomFieldsGroup
            inversedBy: customFields
#TODO: add an unique constraint slug+customFieldsGroup