Chill\CustomFieldsBundle\Entity\CustomFieldsGroup:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: json_array
        entity:
            type: string
            length: 255
        options:
            type: json_array
    oneToMany:
        customFields:
            orderBy: { 'ordering': 'ASC' }
            targetEntity: Chill\CustomFieldsBundle\Entity\CustomField
            mappedBy: customFieldGroup