chill_customfields_customfieldsgroup:
    resource: "@ChillCustomFieldsBundle/Resources/config/routing/customfieldsgroup.yml"
    prefix:   /

chill_customfields_customfield:
    resource: "@ChillCustomFieldsBundle/Resources/config/routing/customfield.yml"
    prefix:   /
