parameters:
#    cl_custom_fields.example.class: Chill\CustomFieldsBundle\Example

services:
    chill.custom_fields.routing_loader:
        class: Chill\CustomFieldsBundle\Routing\RoutesLoader
        tags:
            - { name: routing.loader }
    
    chill.custom_field.provider:
        class: Chill\CustomFieldsBundle\Service\CustomFieldProvider
        call:
            - [setContainer, ["@service_container"]]
            
    chill.custom_field.custom_field_choice_type:
        class: Chill\CustomFieldsBundle\Form\CustomFieldType
        arguments:
            - "@chill.custom_field.provider"
            
        tags:
            - { name: 'form.type', alias: 'custom_field_choice' }
            
    chill.custom_field.custom_fields_group_type:
        class: Chill\CustomFieldsBundle\Form\CustomFieldsGroupType
        arguments:
            - %chill_custom_fields.customizables_entities%
            - "@translator"
        tags:
            - { name: 'form.type', alias: 'custom_fields_group' }
            
    chill.custom_field.custom_field_type:
        class: Chill\CustomFieldsBundle\Form\Type\CustomFieldType
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@chill.custom_field.provider"
        tags:
            - { name: 'form.type', alias: 'custom_field' }
    
    chill.custom_field.text:
        class: Chill\CustomFieldsBundle\CustomFields\CustomFieldText
        tags:
            - { name: 'chill.custom_field', type: 'text' }
            
    chill.custom_field.address:
        class: Chill\CustomFieldsBundle\CustomFields\CustomFieldAddress
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: 'chill.custom_field', type: 'address' }
