services:
   - chill/database:latest
 
before_script:
   - composer config github-oauth.github.com $GITHUB_TOKEN
   - composer install --no-interaction
   - cp Tests/Fixtures/App/app/config/parameters.gitlab-ci.yml Tests/Fixtures/App/app/config/parameters.yml
   - ./console.sh --env=test cache:warmup
   - ./console.sh doctrine:migrations:migrate --env=test --no-interaction
   - ./console.sh doctrine:fixtures:load --env=test --no-interaction

test:php-5.6:
   stage: test
   script: phpunit --testdox
test:php-7:
   stage: test
   script: phpunit --testdox
