language: php
php:
- 5.5
- 5.6
- hhvm-nightly
matrix:
  allow_failures:
  - php: hhvm-nightly
addons:
  postgresql: '9.3'
install:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --dev
  - cp Tests/Fixtures/App/app/config/parameters.travis.yml Tests/Fixtures/App/app/config/parameters.yml
before_script:
  - psql -c 'create database test0;' -U postgres
  - "./console.sh --env=test cache:warmup"
  - "./console.sh doctrine:migrations:migrate --no-interaction"
  - "./console.sh doctrine:fixtures:load --no-interaction --env=test"
script: phpunit --coverage-text
notifications:
  email:
  - info@champs-libres.coop
env:
  global:
    secure: MoVsISTKaeamuFNoylDv/nM6NBXBtCoH5tuGwX3RHpRK/zRXh421RgO8z/GTHxGt63r04EfYrsCXXng8fN4ZVA2Bjb9chGAozYZJOSwZ9Vmfjycu3k0v/+hikAj33DT+CEdVk4fggEZh5dcVbaJDRgaUZkwMLUtyCqeiv+J5X68=
