cl_custom_fields_customfieldsgroup:
    resource: "@ChillCustomFieldsBundle/Resources/config/routing/customfieldsgroup.yml"
    prefix:   /customfieldsgroup

cl_custom_fields_blopentity2:
    resource: "@ChillCustomFieldsBundle/Resources/config/routing/blopentity2.yml"
    prefix:   /blopentity2

cl_custom_fields_adress:
    resource: "@ChillCustomFieldsBundle/Resources/config/routing/adress.yml"
    prefix:   /adress

cl_custom_fields_customfield:
    resource: "@ChillCustomFieldsBundle/Resources/config/routing/customfield.yml"
    prefix:   /customfield

cl_custom_fields_blopentity:
    resource: "@ChillCustomFieldsBundle/Resources/config/routing/blopentity.yml"
    prefix:   /

