parameters:
#    cl_custom_fields.example.class: CL\CustomFieldsBundle\Example

services:
#    cl_custom_fields.example:
#        class: %cl_custom_fields.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
