customfield:
    path:     /{_locale}/admin/customfield/
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:index" }
    options:
        menus:
            admin: 
                order: 1000
                label: "CustomFields"

customfield_show:
    path:     /{_locale}/admin/customfield/{id}/show
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:show" }

customfield_new:
    path:     /{_locale}/admin/customfield/new
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:new" }

customfield_create:
    path:     /{_locale}/admin/customfield/create
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:create" }
    requirements: { _method: post }

customfield_edit:
    path:     /{_locale}/admin/customfield/{id}/edit
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:edit" }

customfield_update:
    path:     /{_locale}/admin/customfield/{id}/update
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:update" }
    requirements: { _method: post|put }

customfield_delete:
    path:     /{_locale}/admin/customfield/{id}/delete
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:delete" }
    requirements: { _method: post|delete }
