customfieldsgroup:
    path:     /
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:index" }

customfieldsgroup_show:
    path:     /{id}/show
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:show" }

customfieldsgroup_new:
    path:     /new
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:new" }

customfieldsgroup_create:
    path:     /create
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:create" }
    requirements: { _method: post }

customfieldsgroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:edit" }

customfieldsgroup_update:
    path:     /{id}/update
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:update" }
    requirements: { _method: post|put }

customfieldsgroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:delete" }
    requirements: { _method: post|delete }
