customfieldsgroup:
    path:     /{_locale}/admin/customfieldsgroup/
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:index" }
    options:
        menus:
            admin: 
                order: 1010
                label: "CustomFields Groups"

customfieldsgroup_show:
    path:     /{_locale}/admin/customfieldsgroup/{id}/show
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:show" }

customfieldsgroup_new:
    path:     /{_locale}/admin/customfieldsgroup/new
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:new" }

customfieldsgroup_create:
    path:     /{_locale}/admin/customfieldsgroup/create
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:create" }
    requirements: { _method: post }

customfieldsgroup_edit:
    path:     /{_locale}/admin/customfieldsgroup/{id}/edit
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:edit" }

customfieldsgroup_update:
    path:     /{_locale}/admin/customfieldsgroup/{id}/update
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:update" }
    requirements: { _method: post|put }

customfieldsgroup_delete:
    path:     /{_locale}/admin/customfieldsgroup/{id}/delete
    defaults: { _controller: "ChillCustomFieldsBundle:CustomFieldsGroup:delete" }
    requirements: { _method: post|delete }
