customfield_section:
    path:     /{_locale}/admin/customfield/
    defaults: { _controller: "ChillCustomFieldsBundle:Admin:index" }
    options:
        menus:
            admin_section: 
                order: 1000
                label: "Custom fields configuration"
                icons: ['asterisk']

customfield_new:
    path:     /{_locale}/admin/customfield/new
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:new" }

customfield_create:
    path:     /{_locale}/admin/customfield/create
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:create" }
    requirements: { _method: post }

customfield_edit:
    path:     /{_locale}/admin/customfield/{id}/edit
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:edit" }

customfield_update:
    path:     /{_locale}/admin/customfield/{id}/update
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:update" }
    requirements: { _method: post|put }
