customfield:
    path:     /
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:index" }

customfield_show:
    path:     /{id}/show
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:show" }

customfield_new:
    path:     /new
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:new" }

customfield_create:
    path:     /create
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:create" }
    requirements: { _method: post }

customfield_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:edit" }

customfield_update:
    path:     /{id}/update
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:update" }
    requirements: { _method: post|put }

customfield_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChillCustomFieldsBundle:CustomField:delete" }
    requirements: { _method: post|delete }
